<?php

namespace App\Libraries\FormSchema\Form;

use Modules\Form\Enums\FormEntryTypes;

class MoverForm
{
    public static function schema(): array
    {
        return [
            [
                'name' => 'mover_type',
                'label' => trans('Service Type'),
                'options' => [trans('Private'), trans('Commercial')],
                'default' => trans('Private'),
                'type' => FormEntryTypes::radio->name,
                'placeholder' => '',
                'validation' => ['required'],
            ],
            [
                'name' => 'from_street',
                'label' => trans('From Street Address'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => ['required', 'alpha_num_symbol'], //
                'messages' => [
                    'required'  => trans('Street and house no is required'),
                    'alpha_num' => trans('Field must contain street name and house no'),
                ],
            ],
            [
                'name' => 'from_postal_code',
                'label' => trans('From Postcode'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => ['required'],
                'messages' => ['required'  => trans('From postcode is required')],
            ],
            [
                'name' => 'from_city',
                'label' => trans('From City'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => ['required'],
                'messages' => ['required'  => trans('From city is required')],
            ],
            [
                'name' => 'from_country',
                'label' => trans('From Country'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
            ],

            [
                'name' => 'has_via_address',
                'label' => trans('Via Address'),
                'options' => [],
                'default' => 0,
                'type' => FormEntryTypes::checkbox->name,
                'placeholder' => '',
            ],
            [
                'name' => 'via_street',
                'label' => trans('Via Street Address'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'via_postal_code',
                'label' => trans('Via Postcode'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'via_city',
                'label' => trans('Via City'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'via_country',
                'label' => trans('Via Country'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => [],
            ],

            [
                'name' => 'has_not_to_address',
                'label' => trans('Address not yet known'),
                'options' => [],
                'default' => 0,
                'type' => FormEntryTypes::checkbox->name,
                'placeholder' => trans('Address not yet known'),
                'validation' => [],
            ],
            [
                'name' => 'to_street',
                'label' => trans('To Street Address'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => ['required', 'alpha_num_symbol'], //
                'messages' => [
                    'required'  => trans('Street and house no is required'),
                    'alpha_num' => trans('Field must contain street name and house no'),
                ],
                'related' => 'has_not_to_address',
                'linked' => [false],
            ],
            [
                'name' => 'to_postal_code',
                'label' => trans('To Postcode'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'related' => 'has_not_to_address',
                'linked' => [false],
                'validation' => ['required'],
                'messages' => ['required'  => trans('To postal code is required')],
            ],
            [
                'name' => 'to_city',
                'label' => trans('To City'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => ['required'],
                'related' => 'has_not_to_address',
                'linked' => [false],
                'messages' => ['required'  => trans('To city is required')],
            ],
            [
                'name' => 'to_country',
                'label' => trans('To Country'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
            ],


            [
                'name' => 'from_lives_in',
                'label' => trans('I live in a'),
                'options' => [trans('Apartment'), trans('House')],
                'default' => trans('Apartment'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => ['required'],
            ],
            [
                'name' => 'from_total_persons',
                'label' => trans('Persons'),
                'options' => [trans('1'), trans('2'), trans('3'), trans('4'), trans('5'), trans('6'), trans('7'), trans('more than 7')],
                'default' => trans('1'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => ['required'],
            ],
            [
                'name' => 'from_floor',
                'label' => trans('Floors'),
                'options' => [trans('EG'), trans('1'), trans('2'), trans('3'), trans('4'), trans('5'), trans('6'), trans('more than 6')],
                'default' => '',
                'type' => FormEntryTypes::select->name,
                'placeholder' => trans('Floor'),
                'validation' => [],
            ],
            [
                'name' => 'from_has_elevator',
                'label' => trans('Elevator available'),
                'options' => [],
                'default' => 0,
                'type' => FormEntryTypes::checkbox->name,
                'placeholder' => trans('Elevator available'),
                'validation' => [],
            ],
            [
                'name' => 'from_fit_items_in_elevator',
                'label' => trans('Fit all items in the elevator'),
                'options' => [trans('Yes'), trans('No')],
                'default' => trans('Yes'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'from_elevator_size',
                'label' => trans('Size of the elevator in KG /number of persons'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'from_elevator_size_unit',
                'label' => trans('Size of the elevator unit'),
                'options' => [trans('KG'), trans('Person')],
                'default' => '',
                'type' => FormEntryTypes::select->name,
                'placeholder' => trans('Please select'),
                'validation' => [],
            ],
            [
                'name' => 'from_total_rooms',
                'label' => trans('Rooms'),
                'options' => [trans('1'), trans('1.5'), trans('2'), trans('2.5'), trans('3'), trans('3.5'), trans('4'), trans('4.5'), trans('5'), trans('5.5'), trans('6'), trans('6.5'), trans('7'), trans('more than 7')],
                'default' => '',
                'type' => FormEntryTypes::select->name,
                'placeholder' => trans('Rooms'),
                'validation' => [],
            ],
            [
                'name' => 'from_no_stopping',
                'label' => trans('No stopping'),
                'options' => [trans('Is not necessary'), trans('I set up'), trans('Sets up moving company')],
                'default' => trans('Is not necessary'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => ['required'],
            ],
            [
                'name' => 'from_furniture_disassemble',
                'label' => trans('Disassemble furniture'),
                'options' => [],
                'default' => 0,
                'type' => FormEntryTypes::checkbox->name,
                'placeholder' => trans('Disassemble furniture'),
                'validation' => [],
            ],
            [
                'name' => 'from_furniture_disassemble_detail',
                'label' => trans('What needs to be disassembled?'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::textarea->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'from_living_space',
                'label' => trans('Living space'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => 'm²',
                'validation' => ['required'],
            ],
            [
                'name' => 'from_kitchen_disassemble',
                'label' => trans('Kitchen disassemble'),
                'options' => [],
                'default' => 0,
                'type' => FormEntryTypes::checkbox->name,
                'placeholder' => trans('Kitchen disassemble'),
                'validation' => [],
            ],
            [
                'name' => 'from_kitchen_disassemble_detail',
                'label' => trans('What needs to be disassembled?'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::textarea->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'from_packing_cartons',
                'label' => trans('Packing cartons'),
                'options' => [],
                'default' => 0,
                'type' => FormEntryTypes::checkbox->name,
                'placeholder' => trans('Packing cartons'),
                'validation' => [],
            ],

            [
                'name' => 'to_move_to',
                'label' => trans('I move to a'),
                'options' => [trans('Apartment'), trans('House')],
                'default' => trans('Apartment'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => ['required'],
            ],
            [
                'name' => 'to_floor',
                'label' => trans('Floors'),
                'options' => [trans('EG'),trans('1'), trans('2'), trans('3'), trans('4'), trans('5'), trans('6'), trans('6 higher')],
                'default' => '',
                'type' => FormEntryTypes::select->name,
                'placeholder' => trans('Floor'),
                'validation' => [],
            ],
            [
                'name' => 'to_has_elevator',
                'label' => trans('Elevator available'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::checkbox->name,
                'placeholder' => trans('Elevator available'),
                'validation' => [],
            ],
            [
                'name' => 'to_fit_items_in_elevator',
                'label' => trans('Fit all items in the elevator'),
                'options' => [trans('Yes'), trans('No')],
                'default' => trans('Yes'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'to_elevator_size',
                'label' => trans('Size of the elevator in KG /number of persons'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'to_elevator_size_unit',
                'label' => trans('Size of the elevator unit'),
                'options' => [trans('KG'), trans('Person')],
                'default' => '',
                'type' => FormEntryTypes::select->name,
                'placeholder' => trans('Please select'),
                'validation' => [],
            ],
            [
                'name' => 'to_no_stopping',
                'label' => trans('No stopping'),
                'options' => [trans('Is not necessary'), trans('I set up'), trans('Sets up moving company')],
                'default' => trans('Is not necessary'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'to_furniture_assemble',
                'label' => trans('Assemble furniture'),
                'options' => [],
                'default' => 0,
                'type' => FormEntryTypes::checkbox->name,
                'placeholder' => trans('Assemble furniture'),
                'validation' => [],
            ],
            [
                'name' => 'to_furniture_assemble_detail',
                'label' => trans('Assemble list of furniture'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::textarea->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'to_unpack_boxes',
                'label' => trans('Unpack boxes'),
                'options' => [],
                'default' => 0,
                'type' => FormEntryTypes::checkbox->name,
                'placeholder' => trans('Unpack boxes'),
                'validation' => [],
            ],

            [
                'name' => 'moving_date',
                'label' => trans('Moving date'),
                'options' => [trans('Flexible period'), trans('Fixed rate'), trans('Removal with storage')],
                'default' => trans('Flexible period'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'moving_date_from',
                'label' => trans('From'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::date->name,
                'placeholder' => '',
                'validation' => ['required'],
            ],
            [
                'name' => 'moving_date_to',
                'label' => trans('To'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::date->name,
                'placeholder' => '',
                'validation' => ['required'],
                'related' => 'moving_date',
                'linked' => [trans('Flexible period'), trans('Removal with storage')],
            ],

            [
                'name' => 'reach_title',
                'label' => trans('Title'),
                'options' => [trans('Mr'), trans('Ms'), trans('Company')],
                'default' => trans('Mr'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'reach_name',
                'label' => trans('Name'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => ['required'],
            ],
            [
                'name' => 'reach_telephone',
                'label' => trans('Telephone'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => ['required'],
            ],
            [
                'name' => 'reach_email',
                'label' => trans('E-mail'),
                'options' => [],
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => ['required'],
            ],
            [
                'name' => 'reach_cost',
                'label' => trans('Who will pay the costs?'),
                'options' => [trans('Myself'), trans('Company'), trans('Job Center'), trans('Authority')],
                'default' => trans('Myself'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],

            [
                'name' => 'from_carrying_distance',
                'label' => trans('Carrying distance'),
                'options' => [trans('Up to 20m'), trans('Up to 50m'), trans('About 50m')],
                'default' => trans('Up to 20m'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'from_staircase',
                'label' => trans('Staircase'),
                'options' => [trans('normal (1 to 2 m)'), trans('narrow (under 1 m)'), trans('wide (over 2 m)')],
                'default' => trans('normal (1 to 2 m)'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'from_house_position',
                'label' => trans('House position'),
                'options' => [trans('Front house'), trans('Rear house'), trans('Side wing')],
                'default' => trans('Front house'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'from_loading_note',
                'label' => trans('Notes on loading'),
                'options' => null,
                'default' => '',
                'type' => FormEntryTypes::textarea->name,
                'placeholder' => trans('e.g. further loading address, slope, old building until 1970, no turning possibility...'),
                'validation' => [],
            ],
            [
                'name' => 'to_carrying_distance',
                'label' => trans('Carrying distance'),
                'options' => [trans('Up to 20m'), trans('Up to 50m'), trans('About 50m')],
                'default' => trans('Up to 20m'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'to_staircase',
                'label' => trans('Staircase'),
                'options' => [trans('normal (1 to 2 m)'), trans('narrow (under 1 m)'), trans('wide (over 2 m)')],
                'default' => trans('normal (1 to 2 m)'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'to_house_position',
                'label' => trans('House position'),
                'options' => [trans('Front house'), trans('Rear house'), trans('Side wing')],
                'default' => trans('Front house'),
                'type' => FormEntryTypes::select->name,
                'placeholder' => '',
                'validation' => [],
            ],
            [
                'name' => 'to_loading_note',
                'label' => trans('Notes on loading'),
                'options' => null,
                'default' => '',
                'type' => FormEntryTypes::textarea->name,
                'placeholder' => trans('e.g. further loading address, slope, old building until 1970, no turning possibility...'),
                'validation' => [],
            ],


            [
                'name' => 'living_room_wall_unit',
                'label' => trans('Wall unit (per m of front length)'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.9,
            ],
            [
                'name' => 'living_room_buffet',
                'label' => trans('Buffet, with attachment (per meter)'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.8,
            ],
            [
                'name' => 'living_room_tv_others',
                'label' => trans('TV, Hi-Fi system per unit'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'living_room_wing',
                'label' => trans('Wing'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 2,
            ],
            [
                'name' => 'living_room_solid_desk',
                'label' => trans('Solid desk'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.8,
            ],
            [
                'name' => 'living_room_sideboard_display_case',
                'label' => trans('Secretary, sideboard, display case (per pc.)'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.1,
            ],
            [
                'name' => 'living_room_sofa_couch',
                'label' => trans('Sofa, couch (each seat)'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'living_room_chair',
                'label' => trans('Chair'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'living_room_video_console',
                'label' => trans('Video set, DVD player, console'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'living_room_e_piano',
                'label' => trans('E-Piano'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'living_room_bookshelf',
                'label' => trans('Bookshelf, dismountable (per m)'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'living_room_buffet_without_attachment',
                'label' => trans('Buffet, without attachment (per meter)'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'living_room_living_tv_table',
                'label' => trans('TV table'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'living_room_piano',
                'label' => trans('Piano'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'living_room_desk_not_solid',
                'label' => trans('Desk not solid'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'living_room_arm_chair',
                'label' => trans('Armchair'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.6,
            ],
            [
                'name' => 'living_room_old_clock',
                'label' => trans('Grandfather clock, sewing machine (per piece)'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'living_room_table',
                'label' => trans('Table'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'living_room_cabinet_disassembled',
                'label' => trans('Cabinet, disassembled (per meter)'),
                'options' => null,
                'group' => trans('Living room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.8,
            ],

            [
                'name' => 'cartoon_existing',
                'label' => trans('Moving carton already existing'),
                'options' => null,
                'group' => trans('Moving boxes'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => trans('Already Existing'),
                'validation' => [],
                'unit' => 0.1,
                'show_label' => false,
            ],
            [
                'name' => 'cartoon_needed',
                'label' => trans('Moving carton still needed?'),
                'options' => null,
                'group' => trans('Moving boxes'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => trans('Still Needed?'),
                'validation' => [],
                'unit' => 0.1,
                'show_label' => false,
            ],
            [
                'name' => 'book_boxes_existing',
                'label' => trans('Book boxes already existing'),
                'options' => null,
                'group' => trans('Moving boxes'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => trans('Already Existing'),
                'validation' => [],
                'unit' => 0.1,
                'show_label' => false,
            ],
            [
                'name' => 'book_boxes_needed',
                'label' => trans('Book boxes still needed?'),
                'options' => null,
                'group' => trans('Moving boxes'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => trans('Still Needed?'),
                'validation' => [],
                'unit' => 0.1,
                'show_label' => false,
            ],
            [
                'name' => 'clothes_hanging_cartoon_existing',
                'label' => trans('Clothes hanging cartoon already existing'),
                'options' => null,
                'group' => trans('Moving boxes'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => trans('Already Existing'),
                'validation' => [],
                'unit' => 0.3,
                'show_label' => false,
            ],
            [
                'name' => 'clothes_hanging_cartoon_needed',
                'label' => trans('Clothes hanging cartoon still needed?'),
                'options' => null,
                'group' => trans('Moving boxes'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => trans('Still Needed?'),
                'validation' => [],
                'unit' => 0.3,
                'show_label' => false,
            ],

            [
                'name' => 'workroom_filing_cabinet',
                'label' => trans('Filing cabinet (per meter)'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.9,
            ],
            [
                'name' => 'workroom_edp',
                'label' => trans('EDP - equipment (printer, PC, screen)'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.6,
            ],
            [
                'name' => 'workroom_desk_chair',
                'label' => trans('Desk chair'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.3,
            ],
            [
                'name' => 'workroom_sofa_couch',
                'label' => trans('Sofa, couch (each seat)'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'workroom_copying_machine',
                'label' => trans('Copying machine'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.5,
            ],
            [
                'name' => 'workroom_angle_desk',
                'label' => trans('Angle combination (desk)'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.4,
            ],
            [
                'name' => 'workroom_bookshelf',
                'label' => trans('Bookshelf (per meter)'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'workroom_desk',
                'label' => trans('Desk'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.5,
            ],
            [
                'name' => 'workroom_armchair',
                'label' => trans('Armchair'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.6,
            ],
            [
                'name' => 'workroom_table',
                'label' => trans('Table'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'workroom_sideboard',
                'label' => trans('Sideboard'),
                'options' => null,
                'group' => trans('Workroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.8,
            ],

            [
                'name' => 'bedroom_double_bed',
                'label' => trans('Double bed, complete'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 2,
            ],
            [
                'name' => 'bedroom_single_bed',
                'label' => trans('Single bed, complete'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1,
            ],
            [
                'name' => 'bedroom_tv_table',
                'label' => trans('TV table'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'bedroom_side_table',
                'label' => trans('Bedside table'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'bedroom_cabinet',
                'label' => trans('Cabinet, dismountable (per meter)'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.8,
            ],
            [
                'name' => 'bedroom_sliding_door_cabinet',
                'label' => trans('Sliding door cabinet (per meter)'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.8,
            ],
            [
                'name' => 'bedroom_tv',
                'label' => trans('TV, Hi-Fi (per piece)'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'bedroom_drawers',
                'label' => trans('Chest of drawers / with mirror (per piece)'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.7,
            ],
            [
                'name' => 'bedroom_cabinet_to_door',
                'label' => trans('Cabinet, to 2 doors, not demountable'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.6,
            ],
            [
                'name' => 'bedroom_chair',
                'label' => trans('Chair, stool (per piece)'),
                'options' => null,
                'group' => trans('Bedroom'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.25,
            ],

            [
                'name' => 'guestroom_filing_cabinet',
                'label' => trans('Filing cabinet (per meter)'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'guestroom_bed',
                'label' => trans('Bed, complete'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1,
            ],
            [
                'name' => 'guestroom_bunk_bed',
                'label' => trans('Bunk bed, complete'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.5,
            ],
            [
                'name' => 'guestroom_drawer',
                'label' => trans('Chest of drawers'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.7,
            ],
            [
                'name' => 'guestroom_bedside_table',
                'label' => trans('Bedside table'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'guestroom_dismountable_cabinet',
                'label' => trans('Cabinet, dismountable (per meter)'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.8,
            ],
            [
                'name' => 'guestroom_writing_desk',
                'label' => trans('Writing desk'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.7,
            ],
            [
                'name' => 'guestroom_toy_box',
                'label' => trans('Toy box'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'guestroom_bookshelf',
                'label' => trans('Bookshelf (per meter)'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'guestroom_bedding',
                'label' => trans('Bedding (per bed unit)'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.3,
            ],
            [
                'name' => 'guestroom_baby_crib',
                'label' => trans('Baby crib, complete'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'guestroom_playpen',
                'label' => trans('Playpen'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.1,
            ],
            [
                'name' => 'guestroom_cabinet_to_door',
                'label' => trans('Cabinet, to 2 doors, not demountable'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.6,
            ],
            [
                'name' => 'guestroom_chair',
                'label' => trans('Chair'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'guestroom_sofa',
                'label' => trans('Sofa, couch (each seat)'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'guestroom_table',
                'label' => trans('Table'),
                'options' => null,
                'group' => trans('Children / guest room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],

            [
                'name' => 'kitchen_worktop',
                'label' => trans('Worktop (per meter)'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1,
            ],
            [
                'name' => 'kitchen_buffet_with_top',
                'label' => trans('Buffet, with top (per meter)'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.8,
            ],
            [
                'name' => 'kitchen_corner_bench',
                'label' => trans('Corner bench (per seat)'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'kitchen_refrigerator_120l',
                'label' => trans('Refrigerator up to 120 liters'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'kitchen_top_bottom',
                'label' => trans('Kitchen top/bottom (per door per pc.)'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'kitchen_chair',
                'label' => trans('Chair'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'kitchen_dishwasher',
                'label' => trans('Dishwasher'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'kitchen_bar',
                'label' => trans('Kitchen bar (house bar)'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0,
            ],
            [
                'name' => 'kitchen_broom',
                'label' => trans('Broom cupboard'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.6,
            ],
            [
                'name' => 'kitchen_buffet_without_top',
                'label' => trans('Buffet, without top (per meter)'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1.5,
            ],
            [
                'name' => 'kitchen_stove',
                'label' => trans('Stove with hob'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'kitchen_refrigerator_above120l',
                'label' => trans('Refrigerator over 120 liters'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1,
            ],
            [
                'name' => 'kitchen_microwave',
                'label' => trans('Microwave'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'kitchen_table',
                'label' => trans('Table'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.6,
            ],
            [
                'name' => 'kitchen_freezer',
                'label' => trans('Freezer (separate)'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1,
            ],
            [
                'name' => 'kitchen_sideboard',
                'label' => trans('Sideboard, showcase (per pc.)'),
                'options' => null,
                'group' => trans('Kitchen/dining room'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 1,
            ],

            [
                'name' => 'hall_toilet',
                'label' => trans('Toilet cabinet'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'hall_chair',
                'label' => trans('Chair / stool (per piece)'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'hall_washing_machine',
                'label' => trans('Washing machine / dryer (per piece)'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'hall_ironing_board',
                'label' => trans('Ironing board, clothes horse'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.1,
            ],
            [
                'name' => 'hall_drawers',
                'label' => trans('Chest of drawers / with mirror (per piece)'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.7,
            ],
            [
                'name' => 'hall_closet',
                'label' => trans('Linen closet'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'hall_cabinet_dismountable',
                'label' => trans('Cabinet dismountable (per meter)'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.8,
            ],
            [
                'name' => 'hall_vacuum_cleaner',
                'label' => trans('Vacuum cleaner'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'hall_wardrobe',
                'label' => trans('Wardrobe, clothes rack (per piece)'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'hall_shoe_cabinet',
                'label' => trans('Shoe cabinet'),
                'options' => null,
                'group' => trans('Bathroom / hall / corridor'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],

            [
                'name' => 'basement_stroller',
                'label' => trans('Stroller'),
                'options' => null,
                'group' => trans('Basement/storage'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.5,
            ],
            [
                'name' => 'basement_shelf_dismountable',
                'label' => trans('Shelf, dismountable (per meter)'),
                'options' => null,
                'group' => trans('Basement/storage'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'basement_ski',
                'label' => trans('Ski'),
                'options' => null,
                'group' => trans('Basement/storage'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'basement_tool_cabinet',
                'label' => trans('Tool cabinet'),
                'options' => null,
                'group' => trans('Basement/storage'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'basement_suitcase',
                'label' => trans('Suitcase'),
                'options' => null,
                'group' => trans('Basement/storage'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.1,
            ],
            [
                'name' => 'basement_sledge',
                'label' => trans('Sledge'),
                'options' => null,
                'group' => trans('Basement/storage'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'basement_workbench',
                'label' => trans('Workbench, dismountable'),
                'options' => null,
                'group' => trans('Basement/storage'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'basement_toolbox',
                'label' => trans('Toolbox'),
                'options' => null,
                'group' => trans('Basement/storage'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.1,
            ],

            [
                'name' => 'garage_car_tires',
                'label' => trans('Car tires'),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'garage_tricycle',
                'label' => trans("Tricycle / children's bike (per piece)"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'garage_foldable_table',
                'label' => trans("Folding table / folding chair"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'garage_can',
                'label' => trans("Garbage can"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'garage_shelf',
                'label' => trans("Shelf, dismountable (per meter)"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'garage_tt_table',
                'label' => trans("Table tennis table"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.3,
            ],
            [
                'name' => 'garage_flower_pot',
                'label' => trans("Flower pot / box (per piece)"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.1,
            ],
            [
                'name' => 'garage_bike',
                'label' => trans("Bike"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.3,
            ],
            [
                'name' => 'garage_ladder',
                'label' => trans("Ladder (per meter)"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.1,
            ],
            [
                'name' => 'garage_motor',
                'label' => trans("Lawn mower hand / motor"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.3,
            ],
            [
                'name' => 'garage_wheelbarrow',
                'label' => trans("Wheelbarrow"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],

            [
                'name' => 'other_ceiling_lamps',
                'label' => trans("Ceiling lamps"),
                'options' => null,
                'group' => trans('Others'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'other_pictures',
                'label' => trans("Pictures (per piece)"),
                'options' => null,
                'group' => trans('Others'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.1,
            ],
            [
                'name' => 'other_plants',
                'label' => trans("Plants (under 1 meter)"),
                'options' => null,
                'group' => trans('Others'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'other_mirror',
                'label' => trans("Mirror"),
                'options' => null,
                'group' => trans('Others'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'other_floor_lamps',
                'label' => trans("Floor lamps"),
                'options' => null,
                'group' => trans('Others'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.2,
            ],
            [
                'name' => 'other_carpet',
                'label' => trans("Carpet"),
                'options' => null,
                'group' => trans('Others'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.3,
            ],
            [
                'name' => 'other_plants_over_1m',
                'label' => trans("Plants (over 1 meter)"),
                'options' => null,
                'group' => trans('Others'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.8,
            ],
            [
                'name' => 'other_fitness_equipment',
                'label' => trans("Fitness / sports equipment"),
                'options' => null,
                'group' => trans('Others'),
                'default' => '',
                'type' => FormEntryTypes::number->name,
                'placeholder' => '',
                'validation' => [],
                'unit' => 0.4,
            ],
            [
                'name' => 'additional_object',
                'label' => trans("What else is important:"),
                'options' => null,
                'group' => trans('Garage/garden/balcony'),
                'default' => '',
                'type' => FormEntryTypes::textarea->name,
                'placeholder' => trans("e.g. additionally a sandbox, garden furniture (4 chairs, 1 table), children's kitchen should be transported..."),
                'validation' => [],
                'unit' => 0.6,
            ],
            [
                'name' => 'total_moving_object',
                'label' => trans("Total Moving Object"),
                'options' => null,
                'default' => '',
                'type' => FormEntryTypes::text->name,
                'placeholder' => '',
                'validation' => [],
            ],

        ];
    }

    public static function getNames(): array
    {
        $names = [];
        foreach (self::schema() as $field) {
            if (isset($field['name'])) {
                $names[] = $field['name'];
            }
        }
        return $names;
    }

    public static function validationMessages(): array
    {
        return [
            "has_preferred_date.required" => trans('Has preferred date is required'),
            "preferred_date.required" => trans('Desired date is required'),
            "preferred_time.required" => trans('Time is required'),
            "service.required" => trans('Service is required'),
            "order_street.required" => trans('Street is required'),
            "order_postal_code.required" => trans('Postal code is required'),
            "order_city.required" => trans('City is required'),
            "order_country.required" => trans('Country is required'),
            "order_living_space.required" => trans('Living space is required'),
            "order_total_rooms.required" => trans('No of rooms is required'),
            "order_evacuation_site.required" => trans('Evacuation location is required'),
            "order_has_basement.required" => trans('Has basement field is required'),
            "order_has_more_storage.required" => trans('Has more storage field is required'),
            "order_floor.required" => trans('Floor is required'),
            "order_has_elevator.required" => trans('Has elevator field is required'),
            "order_stopping_ban.required" => trans('Stopping ban field is required'),
            "contact_first_name.required" => trans('First name is required'),
            "contact_last_name.required" => trans('Last name is required'),
            "contact_company.required" => trans('Company is required'),
            "contact_telephone_no.required" => trans('Telephone no is required'),
            "contact_email.required" => trans('Email is required'),
            "work_note.required" => trans('Note is required'),
            "attachment.required" => trans('Attachment PDF/Image is required'),
            "extra_service.required" => trans('Extra service is required'),
            "terms.required" => trans('Terms must be checked'),
        ];
    }


    public static function getUnitByKey($key)
    {
        foreach (self::schema() as $schema) {
            if ($schema['name'] == $key) {
                return $schema['unit'] ?? '';
            }
        }

        return '';
    }
}